version: '3'

networks:
  proxy:
    driver: bridge

services:

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - proxy


  giovanaalmeida.ga:
    image: giovanacosta/app1:latest
    networks:
      - proxy

  minhaprimeirapagina.html:
    image: giovanacosta/app2:1.0
    networks:
      - proxy
