apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-cm
spec:
  dnsNames:
    - ab.giovanaalmeida.ga
    - c.giovanaalmeida.ga
    - d.giovanaalmeida.ga
  secretName: certificate-cm
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer