apiVersion: v1
kind: Service
metadata:
  name: s-app-c
spec:
  selector:
    app: app-c
  sessionAffinity: None
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  type: ClusterIP