apiVersion: v1
kind: Service
metadata:
  name: s-app-a
spec:
  type: ClusterIP
  selector:
    app: app-a
  sessionAffinity: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443