apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gcluster
  region: us-east-2

vpc:
  id: "vpc-0aa5ee6836d7d61b7"
  securityGroup: "sg-0e9b3b61c21b19490" 
  subnets:
    public:
      us-east-2a: { id: subnet-065fa14b525687dad }
      us-east-2b: { id: subnet-097d5f3e6aa7fd975 }

managedNodeGroups:
  - name: n-workers2
    labels: { role: workers }
    instanceType: t3.medium
    volumeType: gp3
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    privateNetworking: false
    iam: 
      withAddonPolicies:
        autoScaler: true
        certManager: true
        cloudWatch: true
